### ISSUE TITLE
stacked bar chart no longer working

### ISSUE THREAD

**Issue by thepoosh** [jerairrest/react-chartjs-2#388] opened 2019-03-27 12:08 UTC
I saw https://github.com/jerairrest/react-chartjs-2/issues/220 that suggested adding both the `stack` attribute to each data column and `stacked: true` to the axes objects but for some reason this is broken for me

Using the same data in jsfiddle and the original chartjs library does show stacked bars but with this library it doesn't

My input data for this is:
```
const colors = ['#004876', '#0063a0', '#007ecc', '#0093ee', '#82caf8', '#c8e6f4'];
const options = {
    layout: {
      padding: {
        bottom: 0,
        top: 0
      }
    },
    scales: {
      xAxes: [{
        stacked: true,
        gridLines: {
          display: false
        },
      }],
      yAxes: [{
        stacked: true,
          }],
    },
        responsive: true,
          legend: {
            display: true,
            position: 'right',
            labels: {
              fontColor: '#91929b',
              padding: 20
            }
          }
        };
const chartData = {
  labels: ["08-2018", "09-2018", "10-2018", "11-2018"],
  datasets: [{
      label: 'Air',
      data: [20000, 10000, 2000, 25000],
      stack:'1',
      backgroundColor: colors[0],
      borderWidth: 0
    },
    {
      label: 'Express',
      stack: '2',
      data: [20000, 20000, 2000, 25000],
      backgroundColor: colors[1],
      borderWidth: 0
    },
    {
      label: 'LCL',
      data: [5000, 5000, 20000, 25000],
      backgroundColor: colors[2],
      borderWidth: 0,
      stack: '3'
    },
    {
      label: 'FTL',
      data: [20000, 10000, 12000, 25000],
      backgroundColor: colors[3],
      borderWidth: 0,
      stack: '4',
    },
    {
      label: 'LTL',
      data: [20000, 5000, 10000, 25000],
      backgroundColor: colors[4],
      borderWidth: 0,
      stack: '5',
    },
    {
      label: 'FCL',
      data: [5000, 10000, 5000, 25000],
      backgroundColor: colors[5],
      borderWidth: 0,
      stack: '6',
    },
  ]
};

class App extends Component {
 
  render() {
      return ( <div className = "App" >
      <header className = "App-header" >
      <div>
        <Bar 
        data={chartData}
        options={options}
        width={700}
        height={350} />
        </div>
      </header> <
      /div>
    );
  }
}

```

The resulting chart with this library looks like this: 
![Screenshot from 2019-03-27 14-05-49](https://user-images.githubusercontent.com/840516/55074687-a2058580-5099-11e9-8614-c18b0da603d8.png)

while the same code in JSFiddle looks like this: https://jsfiddle.net/tbLv0nf4/5/

**Comment by davie-robertson** [comment] 2019-04-12 11:17
I don't think you want/need stacked on the XAxis are you want stack them vertically on the YAxis

**Comment by bendavismines** [comment] 2019-04-25 19:39
There should be a way to use a previous version (whatever is used in the fiddle) to get it to work right? Unfortunately I can't tell what the fiddle is using

**Comment by cosmith** [comment] 2019-04-30 09:45
This is working fine if you use the format as specified by chartjs (example here: view-source:https://www.chartjs.org/samples/latest/charts/bar/stacked.html)

You don't need `stack: x` in your dataset either. Just `stacked: true` in your `xAxes` and `yAxes`.

**Comment by Chris502** [comment] 2019-05-07 04:48
So i ran into the same issue, and i resolved it by hijacking the component by using the ID 


```
useEffect(() => {
 //using graphQ/Apollo, it needed to wait till query returned before finding/rendering the graph
   if(!isLoading) {
     const ctx = document.getElementById('test')
     ctx.height = 500
   }
  })
 const StackedBarOptions = {
            scales: {
              xAxes: [{
                stacked: true
              }],
              yAxes: [{
                stacked: true
              }],
              maintainAspectRatio: false
            }
          }
return (
                  <Bar
                    ref={chartReference}
                    id={'test'}
                    data={StackedBarData}
                    options={StackedBarOptions}
                  />)
```

It seemed to be buggy when the `width` and `height` prop were set in the component via props

**Comment by jldork** [comment] 2019-07-04 18:40
Was this ever resolved? @thepoosh @cosmith 

I also cannot reproduce a stacked bar chart using the format specified by chartjs.

**Comment by mulraj208** [comment] 2019-07-26 09:07
<Bar data={barChartData} options={barChartOptions} />



const barChartData = {
  labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
  datasets: [
    {
      label: 'Active',
      backgroundColor: '#a88add',
      stack: '2',
      data: [30, 50, 20, 40, 50, 30, 20, 110],
    },
    {
      label: 'Banned',
      backgroundColor: '#0cc2aa',
      stack: '2',
      data: [10, 0, 5, 15, 0, 4, 8, 8],
    },
  ],
};

const barChartOptions = {
  legend: {
    display: false,
  },
  scales: {
    xAxes: [
      {
        stacked: true,
      },
    ],
    yAxes: [
      {
        stacked: true,
      },
    ],
  },
};


"chart.js": "^2.8.0",
"react-chartjs-2": "^2.7.6",

This config works for me.

**Comment by Pringels** [comment] 2019-12-04 13:26
Closing. Reason: older than 6 months and not enough or outdated information supplied. Please re-open this issue if the problem persists, but provide more information. (including a sandbox link if possible)

**Closed by Pringels** 2019-12-04 13:26 UTC

**Comment by sanjeeviraj** [comment] 2019-12-14 11:49
> Was this ever resolved? @thepoosh @cosmith
> 
> I also cannot reproduce a stacked bar chart using the format specified by chartjs.

use stack key in dataset, would solve it like
`datasets: [
      {
        label: 'Low',
        data: [67.8,50,10],
        backgroundColor: '#D6E9C6',
        **stack: arbitraryStackKey**,
      },
      {
        label: 'Moderate',
        data: [20.7,5,9],
        backgroundColor: '#FAEBCC',
        **stack: arbitraryStackKey**,
      },
      {
        label: 'High',
        data: [11.4,9,3],
        backgroundColor: '#EBCCD1',
        **stack: arbitraryStackKey**,
      }
    ]`

**Comment by tmswartz12** [comment] 2020-08-12 17:14
Has someone figured out a solution to the stacked bar example?

Would be awesome if someone could provide a sandbox or example in the docs!

Thanks!

**Comment by jhonnold** [comment] 2020-08-12 21:36
@tmswartz12  mulraj208  has a working solution listed above. They added `stacked: true` to both axes.

**Comment by bptremblay** [comment] 2021-05-27 01:43
Hello! 
Seems like no way to normalize the ticks scales of each Y axis in the stacked chart. I want the heights of each part of the stack to be proportional to one "max value" in the chart. Meaning, if I have THREE OR MORE datasets, I need to get the MAX value of all of them and scale each bar segment proportionally. 
Does that make sense?

**Comment by bptremblay** [comment] 2021-05-27 01:48
Additionally, if  I use one Y scale for each dataset, what happens is only the first 2 are visible. It seems like maybe there's no TDD for a multi-dataset stacked bar?

if each one of my scales is this complex, it seems to fail.
{
    type: 'linear',
    display: true,
    position: 'left',
    id: 'y-axis-1',
    stacked: true,
    gridLines: {
        display: false,
    },
    labels: {
        show: true,
    },
    scaleLabel: {
        display: true,
        labelString: this.props.metricname,
    },
    ticks: {
        min: 0,
        //min: -100,
        //max: dataUnitSuffix === '%' ? 100 : undefined,
        max: undefined,
        autoSkip: false,
        fontSize: 10,
        fontFamily: 'Lucida Console, Monaco, monospace',
        callback: (value) = > {
            return padTicks(value, 4);
        },
    },
}
If I use a simple example where the axes have few properties, it works better, but I have not found any examples anywhere that show the area of the bar segment being displayed proportionally. It seems like each Y tick scale is computed by automatically finding the max just for that series. This is a really disappointing result when your client wants to know at a glance if your numbers are right.

**Comment by bptremblay** [comment] 2021-05-27 01:49
Perhaps the solution is for me to calculate the stack as a percent but still use the real values in the ticks.

**Comment by tamojay-dey** [comment] 2022-07-07 06:30
chart.js: 3.5.0
react-chartjs-2: 3.0.4
react: 17.0.2

I used the same config still could not solve the issue, the bars are not stacking on top of each other. Any proper solution?
