### ISSUE TITLE
`babel-preset-es2015` a requirement?

### ISSUE THREAD

**Issue by zettadam** [jerairrest/react-chartjs-2#193] opened 2017-09-19 00:31 UTC
I'm using `babel-preset-env` to manage my Babel options based on environment. I just installed `react-chartjs-2` and received the following error when building using `webpack` v3 with `babel-loader`:

```
ERROR in ./node_modules/react-chartjs-2/es/index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/.../[my-project]/node_modules/react-chartjs-2"
```

**Comment by jerairrest** [comment] 2017-09-25 00:33
Were you running tests at the time on your node_modules maybe? Webpack should be using the lib/index.js which doesn't have any reference to babel

**Comment by terryoy** [comment] 2018-01-11 08:55
I have the same problem using simply ES6 import like this:

```javascript
import { Line } from 'react-chartjs-2';
```

I also use `babel-preset-env`.

**Comment by prilutskiy** [comment] 2018-01-12 10:57
Possible root cause: #237

**Comment by Pringels** [comment] 2019-12-11 05:57
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.

**Closed by Pringels** 2019-12-11 05:57 UTC
