### ISSUE TITLE
Issue with bar and line chart.

### ISSUE THREAD

**Issue by holzfelix** [jerairrest/react-chartjs-2#423] opened 2019-07-26 13:31 UTC
I tried this example to get working:

https://github.com/jerairrest/react-chartjs-2/blob/master/example/src/components/mix.js

but got this error: https://codesandbox.io/embed/friendly-zhukovsky-rvf4l

![image](https://user-images.githubusercontent.com/6866699/61954909-3802db80-afba-11e9-8b4e-23f792ba0446.png)

**Comment by Pringels** [comment] 2019-12-03 12:47
Duplicate of #441

**Closed by Pringels** 2019-12-03 12:47 UTC
Labels: bug, duplicate
