### ISSUE TITLE
[Bug] changing datasets and returning to the first rendered doesn't work

### ISSUE THREAD

**Issue by Slind14** [jerairrest/react-chartjs-2#218] opened 2017-11-14 16:37 UTC
Hi there,
currently there is a bug where when we change the datasets a few times and want to return to the initial rendered data, it won't work.

The library does modify (in some instances) the data supplied, this results in a corruption of the referenced data. E.g.

1. data=this.state.data.pageviews (displays page views)
2. data=this.state.data.sessions (displays sessions)
3. data=this.state.data.pageviews (displays sessions) => the supplied data was overwritten internally

I'm currently working around this issue by cloning the array/object before supplying. I would like to avoid this performance overhead and gotcha.

**Comment by jerairrest** [comment] 2017-11-14 21:40
So each change is a new object? Are you able to spin up a quick example?

**Comment by Slind14** [comment] 2017-11-14 22:07
Is there some boilerplate/codepen example I could base this off?

**Comment by jerairrest** [comment] 2017-11-15 02:22
I sadly don't have one handy but I'll try to get one together shortly.

**Comment by jerairrest** [comment] 2017-11-15 02:54
A code pen can be found here.

https://codepen.io/anon/pen/Nwvwjy

**Comment by Slind14** [comment] 2017-11-24 06:53
Just a small heads up. I haven't forgotten about this, it's been a busy week. I'll see about it next week.

**Comment by tpbowden** [comment] 2019-05-28 15:31
@jerairrest @Slind14 did you ever find a solution or workaround for this issue?

**Comment by Pringels** [comment] 2019-12-11 05:42
Seems like duplicate of #438 - closing for now

**Closed by Pringels** 2019-12-11 05:42 UTC
