### ISSUE TITLE
Failed to compile ./node_modules/chart.js/Chart.js

### ISSUE THREAD

**Issue by robinHurtado** [jerairrest/react-chartjs-2#233] opened 2018-01-04 21:47 UTC
After making :
 **npm install react-chartjs-2 chart.js --save**
and trying using the library this is the result that appears :
**Failed to compile ./node_modules/chart.js/Chart.js
Module build failed: Error: ENOENT: no such file or directory**

**Comment by jerairrest** [comment] 2018-01-04 21:56
Chart.js is a peer dependency. Please confirm that you have it installed as well

**Comment by robinHurtado** [comment] 2018-01-04 22:58
I have installed char.js but it is lookin for ./node_modules/chart.js/Chart.js and doesn’t found it.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Jeremy Ayerst <notifications@github.com>
Enviado: Thursday, January 4, 2018 4:56:43 PM
Para: jerairrest/react-chartjs-2
Cc: Robin Hurtado Abadia; Author
Asunto: Re: [jerairrest/react-chartjs-2] Failed to compile ./node_modules/chart.js/Chart.js (#233)


Chart.js is a peer dependency. Please confirm that you have it installed as well

**Comment by prilutskiy** [comment] 2018-01-12 10:55
Possible root cause: #237

**Comment by anikakalbrun** [comment] 2018-02-21 16:37
I have the same problem.
My project in build using create-react-app, and I have react-chartjs-2 and chart.js installed.

**Comment by ruhaise** [comment] 2018-05-25 13:32
any update on this issue ?

**Comment by walterqian** [comment] 2018-06-27 22:57
Encountering the same error.

**Comment by DianPermana** [comment] 2018-12-05 02:31
Same problem, anyone here can resolve? (angular7+win10+visualcode+chart (https://valor-software.com/ng2-charts/))

**Comment by sundaraj** [comment] 2019-03-22 08:24
Guys,

The issue seems to be the path is wrong, Kindly go and check inside your node_modules folder before refer the same.

It works fine for me by adding below in to angular.json

 "scripts": ["./node_modules/chart.js/dist/chart.js"], 

**Note:** The lateset version of ng2-charts being served from **dist** folder not from **src** forlder!

**Comment by stbarillas** [comment] 2019-06-02 08:34
I experienced the same issue, and solved it with the following

1.  Renaming "node_modules" to "node_modules_old" 
2. Run npm install
3. Run npm install --save react
4. Run npm install --chart.js
5. Run npm install --react-chartjs-2

**Comment by Pringels** [comment] 2019-12-11 05:35
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.

**Closed by Pringels** 2019-12-11 05:35 UTC

**Comment by sonsinghdev** [comment] 2021-07-09 05:46
Getting the same issue Any Solution
After making :
npm install react-chartjs-2 chart.js --save
and trying using the library this is the result that appears :
Failed to compile ./node_modules/chart.js/Chart.js
Module build failed: Error: ENOENT: no such file or directory

**Comment by ecolara3** [comment] 2021-12-27 18:12
Found the issue:

The documentation uses a captical C in Chart.js, when it should be chart.js

change: 

./node_modules/chart.js/Chart.js => Failed to compile ./node_modules/chart.js/chart.js

Here is the typo in the documentation: https://primefaces.org/primeng/showcase/#/chart

It is in the section of how to add the reference to angular.json file
