### ISSUE TITLE
Chart get distorted when rendered with Observable array

### ISSUE THREAD

**Issue by cijo7** [jerairrest/react-chartjs-2#190] opened 2017-09-11 17:37 UTC
I am not able to use chartjs with MobX data store. The scaling of chart doesn't work quite right when the data is an observable array. does anyone here know why?

Regards!

**Comment by rantecki** [comment] 2018-03-11 06:06
I'm having a very similar problem.  In my case the responsive resize mechanism completely breaks if I access any kind of Mobx observable in the render method.  It appears as though Mobx is removing the resize event handler or something, as it fires once on the initial render and then never fires again.  I've tried various chart.js versions with the same result.  Very frustrating.

**Comment by Pringels** [comment] 2019-12-11 06:03
Seems like duplicate of #438

**Closed by Pringels** 2019-12-11 06:03 UTC
